version: '3.9'
services:
  seq:
    image: datalust/seq
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
  db:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "My!P@ssw0rd1"
      ACCEPT_EULA: "Y"
